feature/mx-1702 improve errors and logs
robert-koch-institut/mex-backend pull request #189
Opened 2024-10-31 12:15 UTC by cutoffthetop

# PR Context
- some additional prep for mx-1702

# Changes
- mute warnings about labels used in queries but missing in graph
- split up search_merged_items_in_graph for better readability
- update cypher queries to use `CALL` clauses with correct variable scope

2024-11-04 08:06 UTC, rababerladuseladim commented on mex/backend/graph/cypher/merge_edges.cql
>      WITH source, edges
```suggestion
```

2024-11-04 08:21 UTC, rababerladuseladim requested changes
During local testing I get a bunch of errors like this: `FAILED tests/graph/test_connector.py::test_fetch_rule_items_empty - neo4j.exceptions.ConfigurationError: Notification filtering is not supported for the Bolt Protocol Version(5, 0). Server Agent 'None'`

Do I need to update my neo4j installation? And if yes: Could you communicate this in the dev channel and update our development setup guidelines?

2024-11-04 08:21 UTC, rababerladuseladim commented on mex/backend/graph/cypher/merge_item.cql
>      WITH current, values
```suggestion
```

2024-11-04 08:21 UTC, rababerladuseladim commented on mex/backend/graph/cypher/merge_edges.cql
>      WITH source, edges
```suggestion
```

2024-11-04 08:24 UTC, rababerladuseladim commented
And while we're at it: What do you think about expanding the setup instructions in the README with the neo4j installation?

2024-11-04 09:14 UTC, cutoffthetop commented on mex/backend/graph/cypher/merge_item.cql
>      WITH current, values
fixed [a83d6c7](https://github.com/robert-koch-institut/mex-backend/pull/189/commits/a83d6c78b152bf862470cd1bf95084576c935abc)

2024-11-04 09:14 UTC, cutoffthetop commented on mex/backend/graph/cypher/merge_edges.cql
>      WITH source, edges
fixed [a83d6c7](https://github.com/robert-koch-institut/mex-backend/pull/189/commits/a83d6c78b152bf862470cd1bf95084576c935abc)

2024-11-04 09:17 UTC, cutoffthetop commented
> Do I need to update my neo4j installation? And if yes: Could you communicate this in the dev channel and update our development setup guidelines?

the notification settings were introduced in neo4j 5.7, so if you were below that you'd had to upgrade. i added a BREAKING point to the changelog, and will post a reminder upon release.
i also added a bulletpoint on upgrading to our guidelines.

> And while we're at it: What do you think about expanding the setup instructions in the README with the neo4j installation?

our setup guide is quite specific to our needs, so i'd leave that in our internal docs. however, i added a short and more general version of it to the readme.

2024-11-08 13:28 UTC, rababerladuseladim submitted a review, later dismissed
All good, merge away!

2024-11-08 13:49 UTC, merged